#!usr/bin/fish

# my attempt to track which colour settings I used to give my
# prompt its look.

# unfinished


set -u tide_time_color brred           # make right side of the prompt red

set -u tide_context_color_ssh ba86ff   # idk

set -u tide_os_color 83ff5d            # make the os colour green

set -u tide_character_color 8e9fff     # idk

set -u tide_pwd_color_dirs ffff00      # idk
set -u tide_pwd_color_anchors ffff00   # idk

set -u tide_git_icon                  # make it cute 
set -u tide_git_color_untracked 9be673
set -u tide_git_color_staged 009f9f
set -u tide_git_color_branch aaaaff
